



#**Aivle 스쿨 지원 질문, 답변 챗봇 만들기**
# 단계3 : 모델링

## 0. 미션

* 워드 임베딩 벡터 기반 머신러닝 분류 모델링
    * 워드 임베딩 모델을 만들고 임베딩 벡터를 생성합니다.
    * 임베딩 벡터를 이용하여 intent를 분류하는 모델링을 수행합니다.
    * 예측된 intent의 답변 중 임의의 하나를 선정하여 출력합니다.
* 챗봇 : 모델의 예측결과(intent)에 따라 답변하는 챗봇 만들기
    * 질문을 입력받아, 답변하는 함수를 생성합니다.

## 1. 환경준비

### (1) 라이브러리 설치

#### 1) 자연어 처리를 위한 라이브러리

In [1]:
#gensim은 자연어 처리를 위한 오픈소스 라이브러리입니다. 토픽 모델링, 워드 임베딩 등 다양한 자연어 처리 기능을 제공
!pip install gensim

Requirement already satisfied: gensim in /usr/local/lib/python3.10/dist-packages (4.3.3)
Requirement already satisfied: numpy<2.0,>=1.18.5 in /usr/local/lib/python3.10/dist-packages (from gensim) (1.26.4)
Requirement already satisfied: scipy<1.14.0,>=1.7.0 in /usr/local/lib/python3.10/dist-packages (from gensim) (1.13.1)
Requirement already satisfied: smart-open>=1.8.1 in /usr/local/lib/python3.10/dist-packages (from gensim) (7.0.4)
Requirement already satisfied: wrapt in /usr/local/lib/python3.10/dist-packages (from smart-open>=1.8.1->gensim) (1.16.0)

#### 2) 형태소 분석을 위한 라이브러리
* 참조 : https://konlpy.org/en/latest/install/

In [2]:
# mecab 설치를 위한 관련 패키지 설치
!apt-get install curl git
!apt-get install build-essential
!apt-get install cmake
!apt-get install g++
!apt-get install flex
!apt-get install bison
!apt-get install python-dev
!pip install cython
!pip install mecab-python

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
curl is already the newest version (7.81.0-1ubuntu1.18).
git is already the newest version (1:2.34.1-1ubuntu1.11).
0 upgraded, 0 newly installed, 0 to remove and 49 not upgraded.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
build-essential is already the newest version (12.9ubuntu3).
0 upgraded, 0 newly installed, 0 to remove and 49 not upgraded.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
cmake is already the newest version (3.22.1-1ubuntu1.22.04.2).
0 upgraded, 0 newly installed, 0 to remove and 49 not upgraded.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
g++ is already the newest version (4:11.2.0-1ubuntu1).
g++ set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 49 not upgraded.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  libfl-dev libfl2
Suggested packages:
  bison flex-doc
The following NEW packages will be installed:
  flex libfl-dev libfl2
0 upgraded, 3 newly installed, 0 to remove and 49 not upgraded.
Need to get 324 kB of archives.
After this operation, 1,148 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/main amd64 flex amd64 2.6.4-8build2 [307 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy/main amd64 libfl2 amd64 2.6.4-8build2 [10.7 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy/main amd64 libfl-dev amd64 2.6.4-8build2 [6,236 B]
Fetched 324 kB in 1s (584 kB/s)
Selecting previously unselected package flex.
(Reading database ... 123614 files and directories currently installed.)
Preparing to unpack .../flex_2.6.4-8build2_amd64.deb ...
Unpacking flex (2.6.4-8build2) ...
Selecting previously unselected package libfl2:amd64.
Preparing to unpack .../libfl2_2.6.4-8build2_amd64.deb ...
Unpacking libfl2:amd64 (2.6.4-8build2) ...
Selecting previously unselected package libfl-dev:amd64.
Preparing to unpack .../libfl-dev_2.6.4-8build2_amd64.deb ...
Unpacking libfl-dev:amd64 (2.6.4-8build2) ...
Setting up flex (2.6.4-8build2) ...
Setting up libfl2:amd64 (2.6.4-8build2) ...
Setting up libfl-dev:amd64 (2.6.4-8build2) ...
Processing triggers for man-db (2.10.2-1) ...
Processing triggers for libc-bin (2.35-0ubuntu3.4) ...
/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_opencl.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_loader.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Suggested packages:
  bison-doc
The following NEW packages will be installed:
  bison
0 upgraded, 1 newly installed, 0 to remove and 49 not upgraded.
Need to get 748 kB of archives.
After this operation, 2,519 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/main amd64 bison amd64 2:3.8.2+dfsg-1build1 [748 kB]
Fetched 748 kB in 1s (1,326 kB/s)
Selecting previously unselected package bison.
(Reading database ... 123704 files and directories currently installed.)
Preparing to unpack .../bison_2%3a3.8.2+dfsg-1build1_amd64.deb ...
Unpacking bison (2:3.8.2+dfsg-1build1) ...
Setting up bison (2:3.8.2+dfsg-1build1) ...
update-alternatives: using /usr/bin/bison.yacc to provide /usr/bin/yacc (yacc) in auto mode
Processing triggers for man-db (2.10.2-1) ...
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package python-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  python2-dev python2 python-dev-is-python3

E: Package 'python-dev' has no installation candidate
Requirement already satisfied: cython in /usr/local/lib/python3.10/dist-packages (3.0.11)
Collecting mecab-python
  Downloading mecab-python-1.0.0.tar.gz (1.3 kB)
  Preparing metadata (setup.py) ... done
Collecting mecab-python3 (from mecab-python)
  Downloading mecab_python3-1.0.9-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.1 kB)
Downloading mecab_python3-1.0.9-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (581 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 581.7/581.7 kB 10.4 MB/s eta 0:00:00
Building wheels for collected packages: mecab-python
  Building wheel for mecab-python (setup.py) ... done
  Created wheel for mecab-python: filename=mecab_python-1.0.0-py3-none-any.whl size=1230 sha256=4583e2391b147ce39e8171bd1713ab854d02db8271d47c24934ea9ca7a698648
  Stored in directory: /root/.cache/pip/wheels/ec/41/c8/ce8fb469be2547ce596c4000613806505dc54c296aae45da71
Successfully built mecab-python
Installing collected packages: mecab-python3, mecab-python
Successfully installed mecab-python-1.0.0 mecab-python3-1.0.9

In [3]:
# 형태소 기반 토크나이징 (Konlpy)
!python3 -m pip install konlpy
# mecab (ubuntu: linux, mac os 기준)
# 다른 os 설치 방법 및 자세한 내용은 다음 참고: https://konlpy.org/ko/latest/install/#id1
!bash <(curl -s https://raw.githubusercontent.com/konlpy/konlpy/master/scripts/mecab.sh)
# !pip install mecab

Collecting konlpy
  Downloading konlpy-0.6.0-py2.py3-none-any.whl.metadata (1.9 kB)
Collecting JPype1>=0.7.0 (from konlpy)
  Downloading JPype1-1.5.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: lxml>=4.1.0 in /usr/local/lib/python3.10/dist-packages (from konlpy) (4.9.4)
Requirement already satisfied: numpy>=1.6 in /usr/local/lib/python3.10/dist-packages (from konlpy) (1.26.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from JPype1>=0.7.0->konlpy) (24.1)
Downloading konlpy-0.6.0-py2.py3-none-any.whl (19.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.4/19.4 MB 48.9 MB/s eta 0:00:00
Downloading JPype1-1.5.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (488 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 488.6/488.6 kB 26.1 MB/s eta 0:00:00
Installing collected packages: JPype1, konlpy
Successfully installed JPype1-1.5.0 konlpy-0.6.0
Install mecab-ko
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 1381k  100 1381k    0     0  1078k      0  0:00:01  0:00:01 --:--:-- 2378k
mecab-0.996-ko-0.9.2/
mecab-0.996-ko-0.9.2/example/
mecab-0.996-ko-0.9.2/example/example.cpp
mecab-0.996-ko-0.9.2/example/example_lattice.cpp
mecab-0.996-ko-0.9.2/example/example_lattice.c
mecab-0.996-ko-0.9.2/example/example.c
mecab-0.996-ko-0.9.2/example/thread_test.cpp
mecab-0.996-ko-0.9.2/mecab-config.in
mecab-0.996-ko-0.9.2/man/
mecab-0.996-ko-0.9.2/man/Makefile.am
mecab-0.996-ko-0.9.2/man/mecab.1
mecab-0.996-ko-0.9.2/man/Makefile.in
mecab-0.996-ko-0.9.2/mecab.iss.in
mecab-0.996-ko-0.9.2/config.guess
mecab-0.996-ko-0.9.2/README
mecab-0.996-ko-0.9.2/COPYING
mecab-0.996-ko-0.9.2/CHANGES.md
mecab-0.996-ko-0.9.2/README.md
mecab-0.996-ko-0.9.2/INSTALL
mecab-0.996-ko-0.9.2/config.sub
mecab-0.996-ko-0.9.2/configure.in
mecab-0.996-ko-0.9.2/swig/
mecab-0.996-ko-0.9.2/swig/Makefile
mecab-0.996-ko-0.9.2/swig/version.h.in
mecab-0.996-ko-0.9.2/swig/version.h
mecab-0.996-ko-0.9.2/swig/MeCab.i
mecab-0.996-ko-0.9.2/aclocal.m4
mecab-0.996-ko-0.9.2/LGPL
mecab-0.996-ko-0.9.2/Makefile.am
mecab-0.996-ko-0.9.2/configure
mecab-0.996-ko-0.9.2/tests/
mecab-0.996-ko-0.9.2/tests/autolink/
mecab-0.996-ko-0.9.2/tests/autolink/unk.def
mecab-0.996-ko-0.9.2/tests/autolink/dicrc
mecab-0.996-ko-0.9.2/tests/autolink/dic.csv
mecab-0.996-ko-0.9.2/tests/autolink/test
mecab-0.996-ko-0.9.2/tests/autolink/char.def
mecab-0.996-ko-0.9.2/tests/autolink/matrix.def
mecab-0.996-ko-0.9.2/tests/autolink/test.gld
mecab-0.996-ko-0.9.2/tests/t9/
mecab-0.996-ko-0.9.2/tests/t9/unk.def
mecab-0.996-ko-0.9.2/tests/t9/ipadic.pl
mecab-0.996-ko-0.9.2/tests/t9/dicrc
mecab-0.996-ko-0.9.2/tests/t9/dic.csv
mecab-0.996-ko-0.9.2/tests/t9/test
mecab-0.996-ko-0.9.2/tests/t9/char.def
mecab-0.996-ko-0.9.2/tests/t9/matrix.def
mecab-0.996-ko-0.9.2/tests/t9/mkdic.pl
mecab-0.996-ko-0.9.2/tests/t9/test.gld
mecab-0.996-ko-0.9.2/tests/cost-train/
mecab-0.996-ko-0.9.2/tests/cost-train/ipa.train
mecab-0.996-ko-0.9.2/tests/cost-train/ipa.test
mecab-0.996-ko-0.9.2/tests/cost-train/seed/
mecab-0.996-ko-0.9.2/tests/cost-train/seed/rewrite.def
mecab-0.996-ko-0.9.2/tests/cost-train/seed/feature.def
mecab-0.996-ko-0.9.2/tests/cost-train/seed/unk.def
mecab-0.996-ko-0.9.2/tests/cost-train/seed/dicrc
mecab-0.996-ko-0.9.2/tests/cost-train/seed/dic.csv
mecab-0.996-ko-0.9.2/tests/cost-train/seed/char.def
mecab-0.996-ko-0.9.2/tests/cost-train/seed/matrix.def
mecab-0.996-ko-0.9.2/tests/run-eval.sh
mecab-0.996-ko-0.9.2/tests/run-cost-train.sh
mecab-0.996-ko-0.9.2/tests/Makefile.am
mecab-0.996-ko-0.9.2/tests/katakana/
mecab-0.996-ko-0.9.2/tests/katakana/unk.def
mecab-0.996-ko-0.9.2/tests/katakana/dicrc
mecab-0.996-ko-0.9.2/tests/katakana/dic.csv
mecab-0.996-ko-0.9.2/tests/katakana/test
mecab-0.996-ko-0.9.2/tests/katakana/char.def
mecab-0.996-ko-0.9.2/tests/katakana/matrix.def
mecab-0.996-ko-0.9.2/tests/katakana/test.gld
mecab-0.996-ko-0.9.2/tests/eval/
mecab-0.996-ko-0.9.2/tests/eval/answer
mecab-0.996-ko-0.9.2/tests/eval/system
mecab-0.996-ko-0.9.2/tests/eval/test.gld
mecab-0.996-ko-0.9.2/tests/shiin/
mecab-0.996-ko-0.9.2/tests/shiin/unk.def
mecab-0.996-ko-0.9.2/tests/shiin/dicrc
mecab-0.996-ko-0.9.2/tests/shiin/dic.csv
mecab-0.996-ko-0.9.2/tests/shiin/test
mecab-0.996-ko-0.9.2/tests/shiin/char.def
mecab-0.996-ko-0.9.2/tests/shiin/matrix.def
mecab-0.996-ko-0.9.2/tests/shiin/mkdic.pl
mecab-0.996-ko-0.9.2/tests/shiin/test.gld
mecab-0.996-ko-0.9.2/tests/latin/
mecab-0.996-ko-0.9.2/tests/latin/unk.def
mecab-0.996-ko-0.9.2/tests/latin/dicrc
mecab-0.996-ko-0.9.2/tests/latin/dic.csv
mecab-0.996-ko-0.9.2/tests/latin/test
mecab-0.996-ko-0.9.2/tests/latin/char.def
mecab-0.996-ko-0.9.2/tests/latin/matrix.def
mecab-0.996-ko-0.9.2/tests/latin/test.gld
mecab-0.996-ko-0.9.2/tests/chartype/
mecab-0.996-ko-0.9.2/tests/chartype/unk.def
mecab-0.996-ko-0.9.2/tests/chartype/dicrc
mecab-0.996-ko-0.9.2/tests/chartype/dic.csv
mecab-0.996-ko-0.9.2/tests/chartype/test
mecab-0.996-ko-0.9.2/tests/chartype/char.def
mecab-0.996-ko-0.9.2/tests/chartype/matrix.def
mecab-0.996-ko-0.9.2/tests/chartype/test.gld
mecab-0.996-ko-0.9.2/tests/run-dics.sh
mecab-0.996-ko-0.9.2/tests/ngram/
mecab-0.996-ko-0.9.2/tests/ngram/unk.def
mecab-0.996-ko-0.9.2/tests/ngram/dicrc
mecab-0.996-ko-0.9.2/tests/ngram/dic.csv
mecab-0.996-ko-0.9.2/tests/ngram/test
mecab-0.996-ko-0.9.2/tests/ngram/char.def
mecab-0.996-ko-0.9.2/tests/ngram/matrix.def
mecab-0.996-ko-0.9.2/tests/ngram/test.gld
mecab-0.996-ko-0.9.2/tests/Makefile.in
mecab-0.996-ko-0.9.2/ltmain.sh
mecab-0.996-ko-0.9.2/config.rpath
mecab-0.996-ko-0.9.2/config.h.in
mecab-0.996-ko-0.9.2/mecabrc.in
mecab-0.996-ko-0.9.2/GPL
mecab-0.996-ko-0.9.2/Makefile.train
mecab-0.996-ko-0.9.2/ChangeLog
mecab-0.996-ko-0.9.2/install-sh
mecab-0.996-ko-0.9.2/AUTHORS
mecab-0.996-ko-0.9.2/doc/
mecab-0.996-ko-0.9.2/doc/bindings.html
mecab-0.996-ko-0.9.2/doc/posid.html
mecab-0.996-ko-0.9.2/doc/unk.html
mecab-0.996-ko-0.9.2/doc/learn.html
mecab-0.996-ko-0.9.2/doc/format.html
mecab-0.996-ko-0.9.2/doc/libmecab.html
mecab-0.996-ko-0.9.2/doc/mecab.css
mecab-0.996-ko-0.9.2/doc/feature.html
mecab-0.996-ko-0.9.2/doc/Makefile.am
mecab-0.996-ko-0.9.2/doc/soft.html
mecab-0.996-ko-0.9.2/doc/en/
mecab-0.996-ko-0.9.2/doc/en/bindings.html
mecab-0.996-ko-0.9.2/doc/dic-detail.html
mecab-0.996-ko-0.9.2/doc/flow.png
mecab-0.996-ko-0.9.2/doc/mecab.html
mecab-0.996-ko-0.9.2/doc/index.html
mecab-0.996-ko-0.9.2/doc/result.png
mecab-0.996-ko-0.9.2/doc/doxygen/
mecab-0.996-ko-0.9.2/doc/doxygen/tab_a.png
mecab-0.996-ko-0.9.2/doc/doxygen/globals_eval.html
mecab-0.996-ko-0.9.2/doc/doxygen/classMeCab_1_1Tagger-members.html
mecab-0.996-ko-0.9.2/doc/doxygen/functions_vars.html
mecab-0.996-ko-0.9.2/doc/doxygen/doxygen.css
mecab-0.996-ko-0.9.2/doc/doxygen/tab_r.gif
mecab-0.996-ko-0.9.2/doc/doxygen/classMeCab_1_1Lattice.html
mecab-0.996-ko-0.9.2/doc/doxygen/functions.html
mecab-0.996-ko-0.9.2/doc/doxygen/classMeCab_1_1Tagger.html
mecab-0.996-ko-0.9.2/doc/doxygen/mecab_8h_source.html
mecab-0.996-ko-0.9.2/doc/doxygen/tabs.css
mecab-0.996-ko-0.9.2/doc/doxygen/nav_f.png
mecab-0.996-ko-0.9.2/doc/doxygen/tab_b.png
mecab-0.996-ko-0.9.2/doc/doxygen/globals.html
mecab-0.996-ko-0.9.2/doc/doxygen/nav_h.png
mecab-0.996-ko-0.9.2/doc/doxygen/tab_h.png
mecab-0.996-ko-0.9.2/doc/doxygen/classMeCab_1_1Model.html
mecab-0.996-ko-0.9.2/doc/doxygen/globals_func.html
mecab-0.996-ko-0.9.2/doc/doxygen/closed.png
mecab-0.996-ko-0.9.2/doc/doxygen/tab_l.gif
mecab-0.996-ko-0.9.2/doc/doxygen/structmecab__path__t-members.html
mecab-0.996-ko-0.9.2/doc/doxygen/functions_func.html
mecab-0.996-ko-0.9.2/doc/doxygen/globals_type.html
mecab-0.996-ko-0.9.2/doc/doxygen/classMeCab_1_1Lattice-members.html
mecab-0.996-ko-0.9.2/doc/doxygen/structmecab__node__t.html
mecab-0.996-ko-0.9.2/doc/doxygen/namespacemembers_func.html
mecab-0.996-ko-0.9.2/doc/doxygen/tab_s.png
mecab-0.996-ko-0.9.2/doc/doxygen/structmecab__dictionary__info__t-members.html
mecab-0.996-ko-0.9.2/doc/doxygen/namespacemembers_type.html
mecab-0.996-ko-0.9.2/doc/doxygen/classMeCab_1_1Model-members.html
mecab-0.996-ko-0.9.2/doc/doxygen/structmecab__dictionary__info__t.html
mecab-0.996-ko-0.9.2/doc/doxygen/namespaces.html
mecab-0.996-ko-0.9.2/doc/doxygen/namespacemembers.html
mecab-0.996-ko-0.9.2/doc/doxygen/namespaceMeCab.html
mecab-0.996-ko-0.9.2/doc/doxygen/structmecab__path__t.html
mecab-0.996-ko-0.9.2/doc/doxygen/files.html
mecab-0.996-ko-0.9.2/doc/doxygen/structmecab__node__t-members.html
mecab-0.996-ko-0.9.2/doc/doxygen/index.html
mecab-0.996-ko-0.9.2/doc/doxygen/annotated.html
mecab-0.996-ko-0.9.2/doc/doxygen/globals_defs.html
mecab-0.996-ko-0.9.2/doc/doxygen/classes.html
mecab-0.996-ko-0.9.2/doc/doxygen/mecab_8h-source.html
mecab-0.996-ko-0.9.2/doc/doxygen/doxygen.png
mecab-0.996-ko-0.9.2/doc/doxygen/tab_b.gif
mecab-0.996-ko-0.9.2/doc/doxygen/bc_s.png
mecab-0.996-ko-0.9.2/doc/doxygen/open.png
mecab-0.996-ko-0.9.2/doc/doxygen/mecab_8h.html
mecab-0.996-ko-0.9.2/doc/dic.html
mecab-0.996-ko-0.9.2/doc/partial.html
mecab-0.996-ko-0.9.2/doc/feature.png
mecab-0.996-ko-0.9.2/doc/Makefile.in
mecab-0.996-ko-0.9.2/missing
mecab-0.996-ko-0.9.2/BSD
mecab-0.996-ko-0.9.2/NEWS
mecab-0.996-ko-0.9.2/mkinstalldirs
mecab-0.996-ko-0.9.2/src/
mecab-0.996-ko-0.9.2/src/dictionary.h
mecab-0.996-ko-0.9.2/src/writer.h
mecab-0.996-ko-0.9.2/src/utils.h
mecab-0.996-ko-0.9.2/src/string_buffer.cpp
mecab-0.996-ko-0.9.2/src/tokenizer.cpp
mecab-0.996-ko-0.9.2/src/make.bat
mecab-0.996-ko-0.9.2/src/mecab.h
mecab-0.996-ko-0.9.2/src/freelist.h
mecab-0.996-ko-0.9.2/src/string_buffer.h
mecab-0.996-ko-0.9.2/src/learner_tagger.h
mecab-0.996-ko-0.9.2/src/dictionary_compiler.cpp
mecab-0.996-ko-0.9.2/src/eval.cpp
mecab-0.996-ko-0.9.2/src/mecab-system-eval.cpp
mecab-0.996-ko-0.9.2/src/darts.h
mecab-0.996-ko-0.9.2/src/param.h
mecab-0.996-ko-0.9.2/src/char_property.h
mecab-0.996-ko-0.9.2/src/learner_node.h
mecab-0.996-ko-0.9.2/src/mecab-dict-gen.cpp
mecab-0.996-ko-0.9.2/src/mecab-dict-index.cpp
mecab-0.996-ko-0.9.2/src/winmain.h
mecab-0.996-ko-0.9.2/src/thread.h
mecab-0.996-ko-0.9.2/src/context_id.cpp
mecab-0.996-ko-0.9.2/src/Makefile.am
mecab-0.996-ko-0.9.2/src/connector.h
mecab-0.996-ko-0.9.2/src/common.h
mecab-0.996-ko-0.9.2/src/dictionary_rewriter.cpp
mecab-0.996-ko-0.9.2/src/Makefile.msvc.in
mecab-0.996-ko-0.9.2/src/dictionary_rewriter.h
mecab-0.996-ko-0.9.2/src/feature_index.h
mecab-0.996-ko-0.9.2/src/iconv_utils.cpp
mecab-0.996-ko-0.9.2/src/char_property.cpp
mecab-0.996-ko-0.9.2/src/mecab-test-gen.cpp
mecab-0.996-ko-0.9.2/src/tagger.cpp
mecab-0.996-ko-0.9.2/src/mecab-cost-train.cpp
mecab-0.996-ko-0.9.2/src/learner.cpp
mecab-0.996-ko-0.9.2/src/dictionary.cpp
mecab-0.996-ko-0.9.2/src/lbfgs.cpp
mecab-0.996-ko-0.9.2/src/ucs.h
mecab-0.996-ko-0.9.2/src/writer.cpp
mecab-0.996-ko-0.9.2/src/learner_tagger.cpp
mecab-0.996-ko-0.9.2/src/lbfgs.h
mecab-0.996-ko-0.9.2/src/libmecab.cpp
mecab-0.996-ko-0.9.2/src/tokenizer.h
mecab-0.996-ko-0.9.2/src/mecab.cpp
mecab-0.996-ko-0.9.2/src/utils.cpp
mecab-0.996-ko-0.9.2/src/dictionary_generator.cpp
mecab-0.996-ko-0.9.2/src/param.cpp
mecab-0.996-ko-0.9.2/src/context_id.h
mecab-0.996-ko-0.9.2/src/mmap.h
mecab-0.996-ko-0.9.2/src/viterbi.h
mecab-0.996-ko-0.9.2/src/viterbi.cpp
mecab-0.996-ko-0.9.2/src/stream_wrapper.h
mecab-0.996-ko-0.9.2/src/feature_index.cpp
mecab-0.996-ko-0.9.2/src/nbest_generator.h
mecab-0.996-ko-0.9.2/src/ucstable.h
mecab-0.996-ko-0.9.2/src/nbest_generator.cpp
mecab-0.996-ko-0.9.2/src/iconv_utils.h
mecab-0.996-ko-0.9.2/src/connector.cpp
mecab-0.996-ko-0.9.2/src/Makefile.in
mecab-0.996-ko-0.9.2/src/scoped_ptr.h
mecab-0.996-ko-0.9.2/Makefile.in
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for style of include used by make... GNU
checking dependency style of gcc... none
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... none
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking whether gcc needs -traditional... no
checking whether make sets $(MAKE)... (cached) yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... dlltool
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for mt... no
checking if : is a manifest tool... no
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for library containing strerror... none required
checking whether byte ordering is bigendian... no
checking for ld used by GCC... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking for shared library run path origin... done
checking for iconv... yes
checking for working iconv... yes
checking for iconv declaration...
         extern size_t iconv (iconv_t cd, char * *inbuf, size_t *inbytesleft, char * *outbuf, size_t *outbytesleft);
checking for ANSI C header files... (cached) yes
checking for an ANSI C-conforming const... yes
checking whether byte ordering is bigendian... (cached) no
checking for string.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for unistd.h... (cached) yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking for stdint.h... (cached) yes
checking for sys/stat.h... (cached) yes
checking sys/mman.h usability... yes
checking sys/mman.h presence... yes
checking for sys/mman.h... yes
checking sys/times.h usability... yes
checking sys/times.h presence... yes
checking for sys/times.h... yes
checking for sys/types.h... (cached) yes
checking dirent.h usability... yes
checking dirent.h presence... yes
checking for dirent.h... yes
checking ctype.h usability... yes
checking ctype.h presence... yes
checking for ctype.h... yes
checking for sys/types.h... (cached) yes
checking io.h usability... no
checking io.h presence... no
checking for io.h... no
checking windows.h usability... no
checking windows.h presence... no
checking for windows.h... no
checking pthread.h usability... yes
checking pthread.h presence... yes
checking for pthread.h... yes
checking for off_t... yes
checking for size_t... yes
checking size of char... 1
checking size of short... 2
checking size of int... 4
checking size of long... 8
checking size of long long... 8
checking size of size_t... 8
checking for size_t... (cached) yes
checking for unsigned long long int... yes
checking for stdlib.h... (cached) yes
checking for unistd.h... (cached) yes
checking for sys/param.h... yes
checking for getpagesize... yes
checking for working mmap... yes
checking for main in -lstdc++... yes
checking for pthread_create in -lpthread... yes
checking for pthread_join in -lpthread... yes
checking for getenv... yes
checking for opendir... yes
checking whether make is GNU Make... yes
checking if g++ supports stl <vector> (required)... yes
checking if g++ supports stl <list> (required)... yes
checking if g++ supports stl <map> (required)... yes
checking if g++ supports stl <set> (required)... yes
checking if g++ supports stl <queue> (required)... yes
checking if g++ supports stl <functional> (required)... yes
checking if g++ supports stl <algorithm> (required)... yes
checking if g++ supports stl <string> (required)... yes
checking if g++ supports stl <iostream> (required)... yes
checking if g++ supports stl <sstream> (required)... yes
checking if g++ supports stl <fstream> (required)... yes
checking if g++ supports template <class T> (required)... yes
checking if g++ supports const_cast<> (required)... yes
checking if g++ supports static_cast<> (required)... yes
checking if g++ supports reinterpret_cast<> (required)... yes
checking if g++ supports namespaces (required) ... yes
checking if g++ supports __thread (optional)... yes
checking if g++ supports template <class T> (required)... yes
checking if g++ supports GCC native atomic operations (optional)... yes
checking if g++ supports OSX native atomic operations (optional)... no
checking if g++ environment provides all required features... yes
configure: creating ./config.status
config.status: creating Makefile

### (2) 데이터 로딩
* 전처리 단계에서 생성한 데이터들을 로딩합니다.
    * train, val, test
* Google Colab 환경에서 진행을 권장합니다.
    * 구글 드라이브 바로 밑에 project 폴더를 만들고,
    * 데이터 파일을 복사해 넣습니다.

#### 1) Google Colab 환경 구축

* 구글 드라이브 연결

In [5]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [6]:
%cd /content/drive/MyDrive/KT_AIVLE/2023.10.30_미니프로젝트6차

/content/drive/MyDrive/KT_AIVLE/2023.10.30_미니프로젝트6차

#### 2) 저장된 데이터 읽어오기
* 저장된 파일들을 불러옵니다.

In [7]:
import joblib

train = joblib.load('train')
val = joblib.load('val')
test = joblib.load('test')

## 2. 전처리

### (0) 텍스트 증강

In [8]:
!pip install ktextaug

Collecting ktextaug
  Downloading ktextaug-0.1.9-py3-none-any.whl.metadata (1.1 kB)
Requirement already satisfied: beautifulsoup4>=4.6.0 in /usr/local/lib/python3.10/dist-packages (from ktextaug) (4.12.3)
Collecting googletrans==3.1.0a0 (from ktextaug)
  Downloading googletrans-3.1.0a0.tar.gz (19 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: konlpy>=0.5.2 in /usr/local/lib/python3.10/dist-packages (from ktextaug) (0.6.0)
Collecting pykomoran>=0.1.5 (from ktextaug)
  Downloading PyKomoran-0.1.6.post1-py3-none-any.whl.metadata (4.9 kB)
Requirement already satisfied: transformers>=2.6.0 in /usr/local/lib/python3.10/dist-packages (from ktextaug) (4.44.2)
Collecting httpx==0.13.3 (from googletrans==3.1.0a0->ktextaug)
  Downloading httpx-0.13.3-py3-none-any.whl.metadata (25 kB)
Requirement already satisfied: certifi in /usr/local/lib/python3.10/dist-packages (from httpx==0.13.3->googletrans==3.1.0a0->ktextaug) (2024.8.30)
Collecting hstspreload (from httpx==0.13.3->googletrans==3.1.0a0->ktextaug)
  Downloading hstspreload-2024.10.1-py3-none-any.whl.metadata (2.1 kB)
Requirement already satisfied: sniffio in /usr/local/lib/python3.10/dist-packages (from httpx==0.13.3->googletrans==3.1.0a0->ktextaug) (1.3.1)
Collecting chardet==3.* (from httpx==0.13.3->googletrans==3.1.0a0->ktextaug)
  Downloading chardet-3.0.4-py2.py3-none-any.whl.metadata (3.2 kB)
Collecting idna==2.* (from httpx==0.13.3->googletrans==3.1.0a0->ktextaug)
  Downloading idna-2.10-py2.py3-none-any.whl.metadata (9.1 kB)
Collecting rfc3986<2,>=1.3 (from httpx==0.13.3->googletrans==3.1.0a0->ktextaug)
  Downloading rfc3986-1.5.0-py2.py3-none-any.whl.metadata (6.5 kB)
Collecting httpcore==0.9.* (from httpx==0.13.3->googletrans==3.1.0a0->ktextaug)
  Downloading httpcore-0.9.1-py3-none-any.whl.metadata (4.6 kB)
Collecting h11<0.10,>=0.8 (from httpcore==0.9.*->httpx==0.13.3->googletrans==3.1.0a0->ktextaug)
  Downloading h11-0.9.0-py2.py3-none-any.whl.metadata (8.1 kB)
Collecting h2==3.* (from httpcore==0.9.*->httpx==0.13.3->googletrans==3.1.0a0->ktextaug)
  Downloading h2-3.2.0-py2.py3-none-any.whl.metadata (32 kB)
Collecting hyperframe<6,>=5.2.0 (from h2==3.*->httpcore==0.9.*->httpx==0.13.3->googletrans==3.1.0a0->ktextaug)
  Downloading hyperframe-5.2.0-py2.py3-none-any.whl.metadata (7.2 kB)
Collecting hpack<4,>=3.0 (from h2==3.*->httpcore==0.9.*->httpx==0.13.3->googletrans==3.1.0a0->ktextaug)
  Downloading hpack-3.0.0-py2.py3-none-any.whl.metadata (7.0 kB)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4>=4.6.0->ktextaug) (2.6)
Requirement already satisfied: JPype1>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from konlpy>=0.5.2->ktextaug) (1.5.0)
Requirement already satisfied: lxml>=4.1.0 in /usr/local/lib/python3.10/dist-packages (from konlpy>=0.5.2->ktextaug) (4.9.4)
Requirement already satisfied: numpy>=1.6 in /usr/local/lib/python3.10/dist-packages (from konlpy>=0.5.2->ktextaug) (1.26.4)
Collecting py4j==0.10.9.2 (from pykomoran>=0.1.5->ktextaug)
  Downloading py4j-0.10.9.2-py2.py3-none-any.whl.metadata (1.3 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from transformers>=2.6.0->ktextaug) (3.16.1)
Requirement already satisfied: huggingface-hub<1.0,>=0.23.2 in /usr/local/lib/python3.10/dist-packages (from transformers>=2.6.0->ktextaug) (0.24.7)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from transformers>=2.6.0->ktextaug) (24.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from transformers>=2.6.0->ktextaug) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers>=2.6.0->ktextaug) (2024.9.11)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from transformers>=2.6.0->ktextaug) (2.32.3)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.10/dist-packages (from transformers>=2.6.0->ktextaug) (0.4.5)
Requirement already satisfied: tokenizers<0.20,>=0.19 in /usr/local/lib/python3.10/dist-packages (from transformers>=2.6.0->ktextaug) (0.19.1)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.10/dist-packages (from transformers>=2.6.0->ktextaug) (4.66.5)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.23.2->transformers>=2.6.0->ktextaug) (2024.6.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.23.2->transformers>=2.6.0->ktextaug) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->transformers>=2.6.0->ktextaug) (3.3.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->transformers>=2.6.0->ktextaug) (2.2.3)
Downloading ktextaug-0.1.9-py3-none-any.whl (152 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 152.2/152.2 kB 6.8 MB/s eta 0:00:00
Downloading httpx-0.13.3-py3-none-any.whl (55 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.1/55.1 kB 3.0 MB/s eta 0:00:00
Downloading chardet-3.0.4-py2.py3-none-any.whl (133 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.4/133.4 kB 8.5 MB/s eta 0:00:00
Downloading httpcore-0.9.1-py3-none-any.whl (42 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.6/42.6 kB 2.7 MB/s eta 0:00:00
Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.8/58.8 kB 3.6 MB/s eta 0:00:00
Downloading h2-3.2.0-py2.py3-none-any.whl (65 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.0/65.0 kB 4.2 MB/s eta 0:00:00
Downloading PyKomoran-0.1.6.post1-py3-none-any.whl (6.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.4/6.4 MB 59.2 MB/s eta 0:00:00
Downloading py4j-0.10.9.2-py2.py3-none-any.whl (198 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 198.8/198.8 kB 11.6 MB/s eta 0:00:00
Downloading rfc3986-1.5.0-py2.py3-none-any.whl (31 kB)
Downloading hstspreload-2024.10.1-py3-none-any.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 40.6 MB/s eta 0:00:00
Downloading h11-0.9.0-py2.py3-none-any.whl (53 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.6/53.6 kB 3.3 MB/s eta 0:00:00
Downloading hpack-3.0.0-py2.py3-none-any.whl (38 kB)
Downloading hyperframe-5.2.0-py2.py3-none-any.whl (12 kB)
Building wheels for collected packages: googletrans
  Building wheel for googletrans (setup.py) ... done
  Created wheel for googletrans: filename=googletrans-3.1.0a0-py3-none-any.whl size=16353 sha256=66e3995fe93170c4fb1b7f46ca9893fea9959c41e93ff169902c49f03e524540
  Stored in directory: /root/.cache/pip/wheels/50/5d/3c/8477d0af4ca2b8b1308812c09f1930863caeebc762fe265a95
Successfully built googletrans
Installing collected packages: rfc3986, py4j, hyperframe, hpack, h11, chardet, pykomoran, idna, hstspreload, h2, httpcore, httpx, googletrans, ktextaug
  Attempting uninstall: py4j
    Found existing installation: py4j 0.10.9.7
    Uninstalling py4j-0.10.9.7:
      Successfully uninstalled py4j-0.10.9.7
  Attempting uninstall: chardet
    Found existing installation: chardet 5.2.0
    Uninstalling chardet-5.2.0:
      Successfully uninstalled chardet-5.2.0
  Attempting uninstall: idna
    Found existing installation: idna 3.10
    Uninstalling idna-3.10:
      Successfully uninstalled idna-3.10
Successfully installed chardet-3.0.4 googletrans-3.1.0a0 h11-0.9.0 h2-3.2.0 hpack-3.0.0 hstspreload-2024.10.1 httpcore-0.9.1 httpx-0.13.3 hyperframe-5.2.0 idna-2.10 ktextaug-0.1.9 py4j-0.10.9.2 pykomoran-0.1.6.post1 rfc3986-1.5.0

In [9]:
from ktextaug import TextAugmentation

sample_text = '달리는 기차 위에 중립은 없다. 미국의 사회 운동가이자 역사학자인 하워드 진이 남긴 격언이다.'
sample_texts = ['프로그램 개발이 끝나고 서비스가 진행된다.', '도움말을 보고 싶다면 --help를 입력하면 된다.']
agent = TextAugmentation(tokenizer="mecab",
                        num_processes=1) # num_process 가 -1 일시 자동으로 가능한 process의 절반으로 할당
print(agent.generate(sample_text))     # default is back_translation
print(agent.generate(sample_texts))

움직이는 기차에는 중립이 없습니다. 이것은 미국 사회 운동가이자 역사가인 하워드 진(Howard Zinn)의 유명한 인용문입니다.

  0%|          | 0/2 [00:00<?, ?it/s]

['프로그램 개발이 완료되면 서비스가 시작됩니다.', '도움말을 보려면 --help를 입력하세요.']

In [29]:
train_aug=train.copy()
train_aug

,intent,Q,A,type,check
0,43,서울 외에도 교육 장소가 있나요?,"KT 에이블스쿨은 전국 어디서나 참여할 수 있도록, 온/오프라인을 병행하여 탄력적으...",1,서울 외에도 교육 장소가 있나요?
1,32,고용보험에 가입되어 있지만 않으면 미취업자로 보나요?,"KT 에이블스쿨은 미취업자를 대상으로 하며, 교육 시작일 기준 재직자는 지원이 불가...",1,고용보험에 가입되어 있지만 않으면 미취업자로 보나요?
2,53,다른 국비지원과 차이점이 있나요?,KT 에이블스쿨에서는 이론/실습 교육에 나아가 기업 실전형 프로젝트를 중심으로 실무...,1,다른 국비지원과 차이점이 있나요?
3,20,회식 했으면 좋겠다.,맛있는거 드세요.,0,회식했으면 좋겠다.
4,9,우울증 생겼어,꾸준히 약 먹고 치료해보세요.,0,우울증 생겼어
...,...,...,...,...,...
1033,52,대면 교육 때 머무를 수 있는 곳이 있나요?,숙소 및 기숙사에 대한 지원은 제공하지 않습니다.,1,대면 교육 때 머무를 수 있는 곳이 있나요?
1034,35,결과발표 이후에 추가합격이 있나요?,현재 KT 에이블스쿨은 추가합격 제도를 운영하고 있지 않습니다.\n향후 추가합격을 ...,1,결과발표 이후에 추가합격이 있나요?
1035,42,교육 수료 시 출석율이 반영되나요?,KT 에이블스쿨은 고용노동부 K-Digital Training 사업으로 운영됨에 따...,1,교육 수료 시 출석률이 반영되나요?
1036,26,번호 따볼까나,용기를 내보세요!,0,번호 따볼까나
1037,32,프리랜서도 신청할 수 있나요?,"KT 에이블스쿨은 미취업자를 대상으로 하며, 교육 시작일 기준 재직자는 지원이 불가...",1,프리랜서도 신청할 수 있나요?

In [30]:
train_aug['check'] = train_aug['check'].apply(lambda x: agent.generate(x))
train_aug['check']

0                서울 외에 교육 장소가 있나요?
1       고용보험에 가입하지 않으면 실업자로 간주되나요?
2                  다른 정부지원금과 다른가요?
3                   회사 회식을 하고 싶어요.
4                         우울증이 있어요
                   ...
1033      대면 학습 중에 머물 수 있는 곳이 있나요?
1034          합격자 발표 후 추가 모집이 있나요?
1035           교육 이수 시 출석률이 반영되나요?
1036              당신의 전화번호를 가져갈까요?
1037               프리랜서도 지원 가능한가요?
Name: check, Length: 1038, dtype: object

In [31]:
import pandas as pd
train=pd.concat([train,train_aug], ignore_index=True)
train

,intent,Q,A,type,check
0,43,서울 외에도 교육 장소가 있나요?,"KT 에이블스쿨은 전국 어디서나 참여할 수 있도록, 온/오프라인을 병행하여 탄력적으...",1,서울 외에도 교육 장소가 있나요?
1,32,고용보험에 가입되어 있지만 않으면 미취업자로 보나요?,"KT 에이블스쿨은 미취업자를 대상으로 하며, 교육 시작일 기준 재직자는 지원이 불가...",1,고용보험에 가입되어 있지만 않으면 미취업자로 보나요?
2,53,다른 국비지원과 차이점이 있나요?,KT 에이블스쿨에서는 이론/실습 교육에 나아가 기업 실전형 프로젝트를 중심으로 실무...,1,다른 국비지원과 차이점이 있나요?
3,20,회식 했으면 좋겠다.,맛있는거 드세요.,0,회식했으면 좋겠다.
4,9,우울증 생겼어,꾸준히 약 먹고 치료해보세요.,0,우울증 생겼어
...,...,...,...,...,...
2071,52,대면 교육 때 머무를 수 있는 곳이 있나요?,숙소 및 기숙사에 대한 지원은 제공하지 않습니다.,1,대면 학습 중에 머물 수 있는 곳이 있나요?
2072,35,결과발표 이후에 추가합격이 있나요?,현재 KT 에이블스쿨은 추가합격 제도를 운영하고 있지 않습니다.\n향후 추가합격을 ...,1,합격자 발표 후 추가 모집이 있나요?
2073,42,교육 수료 시 출석율이 반영되나요?,KT 에이블스쿨은 고용노동부 K-Digital Training 사업으로 운영됨에 따...,1,교육 이수 시 출석률이 반영되나요?
2074,26,번호 따볼까나,용기를 내보세요!,0,당신의 전화번호를 가져갈까요?
2075,32,프리랜서도 신청할 수 있나요?,"KT 에이블스쿨은 미취업자를 대상으로 하며, 교육 시작일 기준 재직자는 지원이 불가...",1,프리랜서도 지원 가능한가요?

In [33]:
train = train.drop_duplicates().reset_index(drop=True)
train

,intent,Q,A,type,check
0,43,서울 외에도 교육 장소가 있나요?,"KT 에이블스쿨은 전국 어디서나 참여할 수 있도록, 온/오프라인을 병행하여 탄력적으...",1,서울 외에도 교육 장소가 있나요?
1,32,고용보험에 가입되어 있지만 않으면 미취업자로 보나요?,"KT 에이블스쿨은 미취업자를 대상으로 하며, 교육 시작일 기준 재직자는 지원이 불가...",1,고용보험에 가입되어 있지만 않으면 미취업자로 보나요?
2,53,다른 국비지원과 차이점이 있나요?,KT 에이블스쿨에서는 이론/실습 교육에 나아가 기업 실전형 프로젝트를 중심으로 실무...,1,다른 국비지원과 차이점이 있나요?
3,20,회식 했으면 좋겠다.,맛있는거 드세요.,0,회식했으면 좋겠다.
4,9,우울증 생겼어,꾸준히 약 먹고 치료해보세요.,0,우울증 생겼어
...,...,...,...,...,...
2000,52,대면 교육 때 머무를 수 있는 곳이 있나요?,숙소 및 기숙사에 대한 지원은 제공하지 않습니다.,1,대면 학습 중에 머물 수 있는 곳이 있나요?
2001,35,결과발표 이후에 추가합격이 있나요?,현재 KT 에이블스쿨은 추가합격 제도를 운영하고 있지 않습니다.\n향후 추가합격을 ...,1,합격자 발표 후 추가 모집이 있나요?
2002,42,교육 수료 시 출석율이 반영되나요?,KT 에이블스쿨은 고용노동부 K-Digital Training 사업으로 운영됨에 따...,1,교육 이수 시 출석률이 반영되나요?
2003,26,번호 따볼까나,용기를 내보세요!,0,당신의 전화번호를 가져갈까요?
2004,32,프리랜서도 신청할 수 있나요?,"KT 에이블스쿨은 미취업자를 대상으로 하며, 교육 시작일 기준 재직자는 지원이 불가...",1,프리랜서도 지원 가능한가요?

### (1) 라벨 조정 및 배열화

In [34]:
train['intent'] = train['intent'] - 1
val['intent'] = val['intent'] - 1
test['intent'] = test['intent'] - 1

X_train = train['check'].values
y_train = train['intent'].values
X_val = val['check'].values
y_val = val['intent'].values
X_test = test['check'].values
y_test = test['intent'].values

### (2) 텍스트 정제 및 Okt 토큰화
* 텍스트 정규화
* 어간 추출
* 불용어 제거

In [35]:
from konlpy.tag import Okt, Komoran, Mecab, Hannanum, Kkma

# 다양한 토크나이저를 사용할 수 있는 함수
def get_tokenizer(tokenizer_name):
    if tokenizer_name == "komoran":
        tokenizer = Komoran()
    elif tokenizer_name == "okt":
        tokenizer = Okt()
    elif tokenizer_name == "mecab":
        tokenizer = Mecab()
    elif tokenizer_name == "hannanum":
        tokenizer = Hannanum()
    else:
        tokenizer = Kkma()

    return tokenizer

In [36]:
import re

def tokenize(tokenizer_name, original_sent, nouns=False):
    tokenizer = get_tokenizer(tokenizer_name)

    cleaned_sent = re.sub(r'[^\sa-zA-Z가-힣]', '', original_sent).lower().strip()
    cleaned_sent = re.sub(r'\s+', ' ', cleaned_sent)

    tokens = tokenizer.morphs(cleaned_sent, norm=True, stem=True)
    stop_words = ['mmm', 'q']
    tokens = [token for token in tokens if token not in stop_words]

    return tokens

In [37]:
tokenizer_name = "okt"
X_train_tokens = [tokenize(tokenizer_name, text) for text in X_train]
X_val_tokens = [tokenize(tokenizer_name, text) for text in X_val]
X_test_tokens = [tokenize(tokenizer_name, text) for text in X_test]

### (3) 수치화
* Keras Tokenizer
* 텍스트 데이터를 숫자 시퀀스로 변환

In [38]:
from tensorflow.keras.preprocessing.text import Tokenizer

tokenizer = Tokenizer()
tokenizer.fit_on_texts(X_train_tokens)

X_train_sequences = tokenizer.texts_to_sequences(X_train_tokens)
X_val_sequences = tokenizer.texts_to_sequences(X_val_tokens)
X_test_sequences = tokenizer.texts_to_sequences(X_test_tokens)

### (4) 패딩
* Keras Tokenizer
* 최대 시퀀스 길이 계산
* 텍스트 데이터를 숫자 시퀀스로 변환

In [39]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

all_tokens = X_train_tokens + X_val_tokens + X_test_tokens

max_sequence_length = max(len(sequence) for sequence in all_tokens)

X_train_pad = pad_sequences(X_train_sequences, maxlen=max_sequence_length)
X_val_pad = pad_sequences(X_val_sequences, maxlen=max_sequence_length)
X_test_pad = pad_sequences(X_test_sequences, maxlen=max_sequence_length)

## 3. 모델링

### (1) 모델 1
* lstm

In [40]:
import numpy as np

embedding_dim = 300
vocab_size = len(tokenizer.word_index) + 1
num_classes = len(np.unique(y_train))

In [42]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, SpatialDropout1D
from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping

# LSTM Model
model = Sequential()
model.add(Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=max_sequence_length))
model.add(SpatialDropout1D(0.2))
model.add(LSTM(100, dropout=0.2, recurrent_dropout=0.2))
model.add(Dense(num_classes, activation='softmax'))

model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

batch_size = 8
epochs = 50

checkpoint = ModelCheckpoint("best_model.keras", monitor='val_accuracy', verbose=1, save_best_only=True, mode='max')

early_stop = EarlyStopping(monitor='val_loss', patience=10, verbose=1, restore_best_weights=True)

history = model.fit(X_train_pad, y_train, batch_size=batch_size, epochs=epochs,
                    validation_data=(X_val_pad, y_val), callbacks=[checkpoint, early_stop])

Epoch 1/50
251/251 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 0.1221 - loss: 3.6925
Epoch 1: val_accuracy improved from -inf to 0.30000, saving model to best_model.keras
251/251 ━━━━━━━━━━━━━━━━━━━━ 32s 98ms/step - accuracy: 0.1223 - loss: 3.6914 - val_accuracy: 0.3000 - val_loss: 2.6276
Epoch 2/50
250/251 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - accuracy: 0.4016 - loss: 2.3079
Epoch 2: val_accuracy improved from 0.30000 to 0.56154, saving model to best_model.keras
251/251 ━━━━━━━━━━━━━━━━━━━━ 38s 86ms/step - accuracy: 0.4022 - loss: 2.3057 - val_accuracy: 0.5615 - val_loss: 1.5480
Epoch 3/50
251/251 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - accuracy: 0.7337 - loss: 1.1365
Epoch 3: val_accuracy improved from 0.56154 to 0.75385, saving model to best_model.keras
251/251 ━━━━━━━━━━━━━━━━━━━━ 41s 88ms/step - accuracy: 0.7338 - loss: 1.1360 - val_accuracy: 0.7538 - val_loss: 1.0008
Epoch 4/50
251/251 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.9139 - loss: 0.4980
Epoch 4: val_accuracy improved from 0.75385 to 0.83077, saving model to best_model.keras
251/251 ━━━━━━━━━━━━━━━━━━━━ 40s 82ms/step - accuracy: 0.9139 - loss: 0.4978 - val_accuracy: 0.8308 - val_loss: 0.7593
Epoch 5/50
251/251 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - accuracy: 0.9554 - loss: 0.2415
Epoch 5: val_accuracy improved from 0.83077 to 0.83846, saving model to best_model.keras
251/251 ━━━━━━━━━━━━━━━━━━━━ 22s 89ms/step - accuracy: 0.9554 - loss: 0.2415 - val_accuracy: 0.8385 - val_loss: 0.7108
Epoch 6/50
251/251 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.9767 - loss: 0.1352
Epoch 6: val_accuracy improved from 0.83846 to 0.84615, saving model to best_model.keras
251/251 ━━━━━━━━━━━━━━━━━━━━ 40s 85ms/step - accuracy: 0.9767 - loss: 0.1352 - val_accuracy: 0.8462 - val_loss: 0.7000
Epoch 7/50
251/251 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 0.9802 - loss: 0.1113
Epoch 7: val_accuracy did not improve from 0.84615
251/251 ━━━━━━━━━━━━━━━━━━━━ 39s 76ms/step - accuracy: 0.9802 - loss: 0.1113 - val_accuracy: 0.8462 - val_loss: 0.6507
Epoch 8/50
251/251 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - accuracy: 0.9907 - loss: 0.0650
Epoch 8: val_accuracy improved from 0.84615 to 0.86154, saving model to best_model.keras
251/251 ━━━━━━━━━━━━━━━━━━━━ 24s 90ms/step - accuracy: 0.9907 - loss: 0.0649 - val_accuracy: 0.8615 - val_loss: 0.6163
Epoch 9/50
251/251 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.9916 - loss: 0.0497
Epoch 9: val_accuracy did not improve from 0.86154
251/251 ━━━━━━━━━━━━━━━━━━━━ 39s 82ms/step - accuracy: 0.9915 - loss: 0.0497 - val_accuracy: 0.8462 - val_loss: 0.6531
Epoch 10/50
251/251 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - accuracy: 0.9916 - loss: 0.0425
Epoch 10: val_accuracy improved from 0.86154 to 0.89231, saving model to best_model.keras
251/251 ━━━━━━━━━━━━━━━━━━━━ 40s 77ms/step - accuracy: 0.9916 - loss: 0.0425 - val_accuracy: 0.8923 - val_loss: 0.6217
Epoch 11/50
251/251 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - accuracy: 0.9921 - loss: 0.0365
Epoch 11: val_accuracy did not improve from 0.89231
251/251 ━━━━━━━━━━━━━━━━━━━━ 24s 91ms/step - accuracy: 0.9921 - loss: 0.0365 - val_accuracy: 0.8615 - val_loss: 0.6426
Epoch 12/50
251/251 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.9917 - loss: 0.0322
Epoch 12: val_accuracy did not improve from 0.89231
251/251 ━━━━━━━━━━━━━━━━━━━━ 21s 82ms/step - accuracy: 0.9917 - loss: 0.0322 - val_accuracy: 0.8692 - val_loss: 0.6433
Epoch 13/50
251/251 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - accuracy: 0.9907 - loss: 0.0328
Epoch 13: val_accuracy did not improve from 0.89231
251/251 ━━━━━━━━━━━━━━━━━━━━ 42s 86ms/step - accuracy: 0.9907 - loss: 0.0328 - val_accuracy: 0.8692 - val_loss: 0.6260
Epoch 14/50
251/251 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 0.9951 - loss: 0.0228
Epoch 14: val_accuracy did not improve from 0.89231
251/251 ━━━━━━━━━━━━━━━━━━━━ 41s 85ms/step - accuracy: 0.9951 - loss: 0.0228 - val_accuracy: 0.8692 - val_loss: 0.6827
Epoch 15/50
251/251 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - accuracy: 0.9938 - loss: 0.0240
Epoch 15: val_accuracy did not improve from 0.89231
251/251 ━━━━━━━━━━━━━━━━━━━━ 39s 77ms/step - accuracy: 0.9938 - loss: 0.0240 - val_accuracy: 0.8615 - val_loss: 0.6816
Epoch 16/50
251/251 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - accuracy: 0.9966 - loss: 0.0162
Epoch 16: val_accuracy did not improve from 0.89231
251/251 ━━━━━━━━━━━━━━━━━━━━ 23s 89ms/step - accuracy: 0.9966 - loss: 0.0163 - val_accuracy: 0.8615 - val_loss: 0.6680
Epoch 17/50
251/251 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.9940 - loss: 0.0222
Epoch 17: val_accuracy did not improve from 0.89231
251/251 ━━━━━━━━━━━━━━━━━━━━ 39s 83ms/step - accuracy: 0.9940 - loss: 0.0222 - val_accuracy: 0.8769 - val_loss: 0.6539
Epoch 18/50
251/251 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - accuracy: 0.9907 - loss: 0.0235
Epoch 18: val_accuracy did not improve from 0.89231
251/251 ━━━━━━━━━━━━━━━━━━━━ 39s 77ms/step - accuracy: 0.9907 - loss: 0.0235 - val_accuracy: 0.8615 - val_loss: 0.7181
Epoch 18: early stopping
Restoring model weights from the end of the best epoch: 8.

In [43]:
from tensorflow.keras.models import load_model

best_model = load_model("best_model.keras")

accuracy = best_model.evaluate(X_test_pad, y_test)[1]
print("Best Model Test Accuracy:", accuracy)

5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - accuracy: 0.8710 - loss: 0.5306
Best Model Test Accuracy: 0.8538461327552795

In [44]:
best_model.save("model.keras")

## 4. 챗봇
* **상세요구사항**
    * 챗봇 flow : input 질문 -> 분류 모델로 intent 예측 --> intent에 해당하는 답변 출력
        * 하나의 intent 에는 여러 답변이 있습니다. 이중 한가지를 랜덤하게 선택합니다.

#### 1) 사용자 입력 테스트

In [46]:
import numpy as np
from grammer_checker import spell_check
from tensorflow.keras.models import load_model

model = load_model("model.keras")


# 입력 전처리 및 예측 함수
def predict_answer(model, input_text):
    checked_text = spell_check(input_text)
    tokens = tokenize("okt", checked_text)
    sequences = tokenizer.texts_to_sequences([tokens])
    padded_sequences = pad_sequences(sequences, maxlen=max_sequence_length)
    prediction = model.predict(padded_sequences)
    predicted_class = np.argmax(prediction)
    answer = train.loc[train['intent']==predicted_class]['A'].unique()[0]
    return answer

In [47]:
predict_answer(model,"지원 조건 궁금해요")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 333ms/step

'KT 에이블스쿨은 정규 4년제 대학 졸업자 및 졸업예정자 중 만 34세 이하 미취업자를 대상으로 하는 교육입니다.\n단, 모집시점에 만 35세여도 해당연도 1월 1일 이후 생일자는 지원이 가능합니다.\n또한 전공의 종류와는 무관 합니다.'

#### 2) 챗봇 함수 만들기
* 테스트 코드를 바탕으로 질문을 받아 답변을 하는 함수를 생성합시다.
* 성능이 좋은 모델 사용.

In [48]:
# 대화 함수
def chatbot():
    print("챗봇과 대화를 시작합니다. 종료하려면 '종료'라고 입력하세요.\n")
    while True:
        user_input = input("사용자: ")
        if user_input == '종료':
            print("챗봇과의 대화를 종료합니다.")
            break
        answer = predict_answer(model, user_input)
        print(f"챗봇: {answer}", '\n\n==============================================\n')

In [50]:
chatbot()

챗봇과 대화를 시작합니다. 종료하려면 '종료'라고 입력하세요.

사용자: 학교 수업과 교육을 병행할 수 있어?
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
챗봇: KT 에이블스쿨은 풀타임(09:00~18:00)으로 교육이 진행되며, 정해진 시간에 필수로 참여해야 합니다.
교육에 풀타임으로 참여할 수 있어야 교육 수강이 가능합니다.

==============================================

사용자: 온라인 교육인가?
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
챗봇: 교육 과정 중 STEP1과 STEP2는 대부분 비대면 교육으로 진행하며, 일부 프로젝트는 대면으로 진행될 수 있습니다. STEP3 프로젝트 수행기간에는 대면 & 비대면을 병행하여 진행합니다. (단, 코로나 정부방역지침에 따라 변경될 수 있습니다.)

==============================================

사용자: 나 오늘 상 탔어!
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step
챗봇: 축하드려요!

==============================================

사용자: 핸드폰이 고장났어
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
챗봇: AS센터에 맡겨보세요.

==============================================

사용자: 산책 갈까?
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
챗봇: 좋은 생각입니다.

==============================================

사용자: 종료
챗봇과의 대화를 종료합니다.

* **
* 최종 정확도 : 85%